### ISSUE TITLE
Call to a member function set() on null

### ISSUE THREAD

**Issue by JanPetterMG** [sagarrabadiya/outlook-php#12]
Tried the [example](https://github.com/sagarrabadiya/outlook-php#authenticator) in the readme, but got this error...
Seems like some (unknown) class isn't constructed at time of a member function call.

Version 0.1.5
PHP 7.2.14

```
Fatal error:  Uncaught Error: Call to a member function set() on null in /vendor/sagar/outlook-php/src/Outlook/Authorizer/Authenticator.php:111
Stack trace:
#0 Outlook\Authorizer\Authenticator->getToken()
#1 {main}
thrown in /vendor/sagar/outlook-php/src/Outlook/Authorizer/Authenticator.php on line 111
```

**Comment by sagarrabadiya** [comment]
I think you forgot to set session manager, before getToken you should provide which session manager you want to use, there is one session manager built in for ex. check https://github.com/sagarrabadiya/outlook-php/blob/master/examples/calendar.php

**Comment by JanPetterMG** [comment]
Thanks for the quick reply. This issue is now resolved (kind of)

I'm now facing two new issues...

When I'm logged in to my **organisation** account, via an app ID created on my **private** Microsoft account, I'll get the following error, probably due to import of the wrong namespace... Submitting an PR for this one.
````
Fatal error: Uncaught Error: Class 'Outlook\Exceptions\Calenders\RestApiException' not found in /var/www/jpg/vendor/sagar/outlook-php/src/Outlook/Calendars/CalendarManager.php:65
Stack trace:
#0 /var/www/jpg/www/admin/temp/ocal.php(41): Outlook\Calendars\CalendarManager->getAllCalendars()
#1 {main}
thrown in /var/www/jpg/vendor/sagar/outlook-php/src/Outlook/Calendars/CalendarManager.php on line 65
````


Trying to log in to the same organisation account, using an app ID registered using **the same** organisation account, I'll get this error:
> AADSTS50194: Application 'xxxxxxxxxx' is not configured as a multi-tenant application. Usage of the /common endpoint is not supported for such applications created after '10/15/2018'. Use a tenant-specific endpoint or configure the application to be multi-tenant.

[Microsoft site](https://docs.microsoft.com/en-us/azure/active-directory/develop/howto-convert-app-to-be-multi-tenant#update-registration-to-be-multi-tenant) states the following:
> By default, web app/API registrations in Azure AD are single tenant. You can make your registration multi-tenant by finding the Multi-Tenanted switch on the Properties pane of your application registration in the Azure portal and setting it to Yes.

There is only one problem, there is no Properties pane, and I can't find the option elsewhere either...

Any suggestions?

**Comment by sagarrabadiya** [comment]
Sure, I would be very happy and appreciate the PRs for new features.

**Comment by sagarrabadiya** [comment]
rest api exception class issue has been fixed with 0.1.6 release.

**Comment by sagarrabadiya** [comment]
for multi tenant related error can you open new issue please?

**Comment by JanPetterMG** [comment]
Btw as mentioned, it was the first example in the readme I've used, so this code should also be updated or removed, before this issue is fully resolved.
https://github.com/sagarrabadiya/outlook-php#authenticator
