### ISSUE TITLE
How to get new access token using refresh token?

### ISSUE THREAD

**Issue by JacquilineJaison** [sagarrabadiya/outlook-php#2]
My access token expired.
How can I get the new access token using refresh token ?
Please help

**Comment by sagarrabadiya** [comment]
you can do it using `$eventAuthorizer->renewToken();` for ex. check the examples/events.php, to have successful renew token, there should be existing token in session. else it will return false instead of token

**Comment by sagarrabadiya** [comment]
just published new version of package `0.1.2` upgrade the package and you should good to use `$eventAuthorizer->renewToken()` method

**Comment by sagarrabadiya** [comment]
Thanks for using this package :)

**Comment by JacquilineJaison** [comment]
thanks for the quick reply
