### ISSUE TITLE
How to get the Outlook calendar list of an outlook account after authorization?

### ISSUE THREAD

**Issue by JacquilineJaison** [sagarrabadiya/outlook-php#3]
How to get the edit permissible calendars separately?
Also,the Outlook username and email of the authorised account?

**Comment by sagarrabadiya** [comment]
each received calendar has `canEdit` flag so you can filter from the list of calendars where `canEdit` is `true` and along with calendar item you also receives the owner of that calendar, I don't think outlook support parameter filter in the get api

**Comment by active123456** [comment]
I meant which function should I use in your library to get the calendar list?

**Comment by sagarrabadiya** [comment]
can you add method for getting all calendars in calendarmanager.php you can get calendars api here https://docs.microsoft.com/en-us/previous-versions/office/office-365-api/api/version-2.0/calendar-rest-operations#GetCalendars so add method which calls like `/me/calendars` and send pull request that would help me to publish new version of package.

**Comment by JacquilineJaison** [comment]
When I use the calendar manager  class and call all,I only get the events in my primary calendar.
But I need the entire calendar list not the events.
Please help.

**Comment by JacquilineJaison** [comment]
public function all()
    {
        $response = $this->api->call('/me/calendars', 'get');
        if (isset($response->error)) {
            throw new RestApiException($response->error->message, $response->statusCode);
        }
        return $this->parseEvents($response->value);
    }

**Comment by sagarrabadiya** [comment]
yes seems correct, just change the method name like public function getAllCalendars() and it should work. once its working send the pull request and i will publish new version of package so you can update the package in composer.json file.

**Comment by JacquilineJaison** [comment]
I am using the system provided by the company I work for.
So,don't have the permission to push to github repository like yours.
Could you please make the changes and give an updated version with  the get calendar list function?

**Comment by sagarrabadiya** [comment]
updated package get `0.1.3` and you will have `$calendarManager->getAllCalendars()` method, check the `examples/calendar.php` file `getAllCalendars()` will return you the array of all calendars associated with the current user.

**Comment by JacquilineJaison** [comment]
Thanks a lot!!!.
