### ISSUE TITLE
How to pass state parameter along with the authorization request?

### ISSUE THREAD

**Issue by JacquilineJaison** [sagarrabadiya/outlook-php#4]
Could you please add this feature too?

**Comment by sagarrabadiya** [comment]
what do you mean by state parameter? are you talking about scopes?

**Comment by JacquilineJaison** [comment]
No.
Its another parameter which you can specify along with redirect uri and scopes  while requesting.
Its mentioned here 'https://docs.microsoft.com/en-us/outlook/rest/php-tutorial'

authorization URL:
https://login.microsoftonline.com/common/oauth2/v2.0/authorize?state=48b0ad0b3b443a543cf823f98db760c4&scope=openid%20profile%20offline_access%20User.Read%20Mail.Read&response_type=code&approval_prompt=auto&redirect_uri=http%3A%2F%2Flocalhost%3A8000%2Foauth&client_id=<YOUR_CLIENT_ID>

**Comment by sagarrabadiya** [comment]
update the package and you can give additionalParams as array as 2nd argument to `getLoginUrl()`, for ex. `$eventAuthorizer->getLoginUrl($redirectUri, ['state' => 'value'])` if you don't want to give redirectUri then pass `null` as 1st argument

**Comment by JacquilineJaison** [comment]
I tried to pass the state parameter as an array in $eventAuthorizer->getLoginUrl($redirectUri, ['state' => 'value']).
But it is getting added to scope array.

Error message:-
AADSTS70011: The provided value for the input parameter 'scope' is not valid. The scope https://outlook.office.com/calendars.readwrite openid offline_accessstate=sample is not valid. The scope format is invalid. Scope must be in a valid URI form <https://example/scope> or a valid Guid <guid/scope>.

**Comment by sagarrabadiya** [comment]
check now, update package again.

**Comment by JacquilineJaison** [comment]
Thanks!!!
Works just fine....

**Comment by sagarrabadiya** [comment]
👍 consider giving a star if the package has helped you.. :)

**Comment by JacquilineJaison** [comment]
Done :)
