### ISSUE TITLE
Not getting renewed access token using refresh token.

### ISSUE THREAD

**Issue by JacquilineJaison** [sagarrabadiya/outlook-php#6]
use GuzzleHttp\Client;
 private function getToken($grantType,$code){
        try{       
            $parameterName = $grantType;
            if (strcmp($parameterName, 'authorization_code') == 0) {
                $parameterName = 'code';
            }
            $httpClient = new \GuzzleHttp\Client();        
            $params = [
                "grant_type" => $grantType,
                $parameterName => $code,
                "redirect_uri" => REDIRECT_URI_OUTLOOK,
                "scope" => implode(" ", ['openid', 'offline_access']),
                "client_id" => APP_ID_OUTLOOK,
                "client_secret" => APP_PASSWORD_OUTLOOK
            ];              
            
            $response = $httpClient->post("https://login.microsoftonline.com/common/oauth2/v2.0/token",
                                        ['form_params' => $params]);
            $token = $response->getBody()->getContents();
            return $token;
        } catch (Exception $e) {
        } 
    }

  getToken('refresh_token',$refreshToken);

**Comment by sagarrabadiya** [comment]
you can use directly `$eventAuthorizer->renewToken()` method which will return you new access token or false, above seems you have created custom function I don't think you need this custom function, instead call renewToken() method with your Authorizer instance

**Comment by JacquilineJaison** [comment]
Actually I am not using session to store tokens.Instead I am storing in database.Hence,can't use the $eventAuthorizer->renewToken() method.

**Comment by sagarrabadiya** [comment]
Oh, ok, can you check the $e in your catch block what error are you getting, in most cases its the scope mismatch, so the scope you gave for getting access_token, and the scope you are giving to renew token must be exact same.

**Comment by JacquilineJaison** [comment]
I am not getting any errors.Just that new refresh token and id token is returned.But no new access token.

**Comment by sagarrabadiya** [comment]
that is correct, to have access token you need to use atleast one resource scope, currently you are using only `['openid', 'offline_access']` which returns only id_token try adding `'https://outlook.office.com/calendars.readwrite' or any other resource scope and you will get access_token instead of id_token

**Comment by JacquilineJaison** [comment]
That worked just fine.
Thanks.

**Comment by sagarrabadiya** [comment]
👍

**Comment by JacquilineJaison** [comment]
I got new access token.
But when try to get calendar list,I get 401 response.

**Comment by sagarrabadiya** [comment]
to use calendar list api, your code must be retrived with `https://outlook.office.com/calendars.readwrite` this scope and when getting access token you need to pass this scope, else your token won't be able to access that api

**Comment by JacquilineJaison** [comment]
I had  used  'Calendars.Readwrite' instead of  'https://outlook.office.com/calendars.readwrite' scope.
