### ISSUE TITLE
Login After i am not able to Build proper Token

### ISSUE THREAD

**Issue by kmd1992** [sagarrabadiya/outlook-php#8]
i receive $_GET['code'] variable value form my Redirect URL
but after not execute try block it is direct it's catch block execute, so why am i not able to get proper success response.  
here is issue file located:   src/Outlook/Authorizer/Authenticator.php

        try {
                $response = $httpClient->post($this->authority.$this->tokenUrl, [
                    'form_params' => $params
                ]);
                // we got token successfully save it to session
                $tokenResponse = $this->deserialize($response->getBody()->getContents());
                $token = $this->buildTokenInstance($tokenResponse);
                $this->sessionManager->set($token);
                return $token;
            } catch (\Exception $e) {
                throw new TokenException($e->getMessage(), $e->getCode(), $e);
            }

here is my Response:
![outlookissue2](https://user-images.githubusercontent.com/44061981/46810234-d2789200-cd8d-11e8-8820-150efcc79028.jpg)

**Comment by sagarrabadiya** [comment]
Hi, sorry I was away, anyway from your image it seems the authentication request is not correct either redirect uri doesnt match with the one defined in the app at microsoft or, the scope used for getting code and scope for getting token from code must be same, and for this package you should not use Authenticator directly instead use eventauthorizer and eventmanager class to successfully authenticate and get events Authenticator class is stand alone base class. also the http request to microsoft sent response as unauthorized_client error so double check your request with abobe or check events example to get how to use it. :)

**Comment by kmd1992** [comment]
Thanks for giving reply me,
I am relay  Sorry about that. so now It's resolved and it's my mistake for creation of App/Client ID from Microsoft Developer Account. but still i have a confusing on Get **All Calendar** Data it's perfectly work , but **My Calendar** without another all Calendar Events not get means it's only get **My Calendar** Events. 
So How can i Get All Events form Different Calendar. with perform operation for Add, Edit and also Delete.
So Help Me...

**Comment by sagarrabadiya** [comment]
as this is resolved, closing this
