### ISSUE TITLE
Does the login/authentication work as a service?

### ISSUE THREAD

**Issue by GenieTim** [sagarrabadiya/outlook-php#9]
The authentication instructions in the README seem to be the ones corresponding to the login as a user, is that correct? Could you please give me a hint if any of your code can be extended/reused for the [login as a service](https://developer.microsoft.com/en-us/graph/docs/concepts/auth_v2_service)? I will implement it and open a PR if you want (and if I am not misunderstanding something).

**Comment by sagarrabadiya** [comment]
I think, if you dont pass scope other than `['openid', 'offline_access']` then the api only returns the `id_token` and not the access_token, to get the access token you must pass a valid scope, so when you get login url from authenticator give it scope of array as param and it should work, also you need to set session manager for the authenticator to work correctly also this example usage to get events might give you better idea regarding usage https://github.com/sagarrabadiya/outlook-php/blob/master/examples/events.php

the authorizer for eventmanager internally uses the authenticator instance only by passing some additional scope related to calendar, if this doesnt fit in your scenario, then pull request are most welcome.. 🙂

**Comment by GenieTim** [comment]
Thanks for the response. My changes are in #10, although I have to admit that I now finally settled with https://github.com/microsoftgraph/msgraph-sdk-php and a custom authenticator instead, so no need to accept the PR - just to show others. Thanks very much!
